/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  mainSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsible: false,
      items: ["introduction", "installation"],
    },
    {
      type: "category",
      label: "Configuration",
      collapsible: false,
      items: [
        "configuration",
        "security",
        "networking",
        "cluster",
        "server-settings",
      ],
    },
    {
      type: "category",
      label: "Features",
      collapsible: false,
      items: [
        "admin-ui",
        "streams",
        "indexes",
        "projections",
        "persistent-subscriptions",
      ],
    },
    {
      type: "category",
      label: "Operations",
      collapsible: false,
      items: ["operations", "diagnostics"],
    },
  ],
  httpSidebar: [
    "http-api/http-introduction",
    "http-api/http-security",
    "http-api/http-persistent",
    "http-api/http-projections",
    "http-api/optional-http-headers",
    "http-api/http-api",
  ],
};

export default sidebars;
